apiVersion: apps/v1
kind: Deployment
metadata:
    name: ng1
    namespace: groot
spec:
    selector:
        matchLabels:
            app: nginx
    replicas: 1
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - name: ngx
                  image: nginx:1.18-alpine
                  imagePullPolicy: IfNotPresent
                  command: ["/abc"]








